### ISSUE TITLE
Save position state

### ISSUE THREAD

**Issue by kolmakovruslan** [lisawray/groupie#101]
Save Group scroll position state after data set change

**Comment by lisawray** [comment]
You don't have to do anything special for Groupie.  You can just use the normal methods you would with any RecyclerView.  

To save state:
`int scrollPosition = layoutManager.findFirstVisibleItemPosition()` [LinearLayoutManager](https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#findFirstVisibleItemPosition())

To restore state:
`layoutManager.scrollToPosition(scrollPosition)`

**Comment by kolmakovruslan** [comment]
@lisawray thanks!

**Comment by ismdcf** [comment]
Using the above method if you have more items on your group the view will snap to start of the group. To overcome this you could use layoutManager.onSaveInstanceState()

To save state:
`Parcelable layoutManagerState = layoutManager.onSaveInstanceState();`

To restore state:
`layoutManager.onRestoreInstanceState(layoutManagerState);`

Kudos
