### ISSUE TITLE
Failed to resolve: com.xwray:groupie:2.0.0-alpha2

### ISSUE THREAD

**Issue by sotrh** [lisawray/groupie#102]
My gradle build was failing when I included this dependency on my project at work. The same happened when I created a new empty project. It builds fine with `'com.xwray:groupie:2.0.0-alpha1'` though.

*Edit:
This issue also happens with `'com.xwray:groupie-databinding:2.0.0-alpha2'`

**Comment by lisawray** [comment]
Weird!  It looks like the script didn't complete.  

I confirmed 2.0.0-alpha2 is now on Bintray (https://bintray.com/lisawray/maven/groupie/2.0.0-alpha2) so it should be on jcenter shortly.  

Thank you for the catch!

**Comment by lisawray** [comment]
Just confirmed it's up on jcenter. Thanks again!
