### ISSUE TITLE
UpdatingGroup update method takes only List

### ISSUE THREAD

**Issue by Pedramrn** [lisawray/groupie#103]
Why not accepting Collections?

**Comment by lisawray** [comment]
The underlying mechanism in UpdatingGroup, DiffUtil, compares lists. In particular, it compares items at particular indices.  Collection is not necessarily ordered and doesn't have methods like `Collection.get(index)`.  So, you can't meaningfully get or compare the old item at index 1 and the new item at index 1, for example.  If you simply want to replace items in a Group with a new Collection of items, you can use a Section.

Hope that makes sense.  I'm closing this for now, but let me know if I can clarify anything else for you.
