### ISSUE TITLE
Remove children from expandable group

### ISSUE THREAD

**Issue by sandeshlasnapure** [lisawray/groupie#107]
How to remove or update children from expandable group?

**Comment by sandeshlasnapure** [comment]
finally managed

**Comment by ovitrif** [comment]
@sandeshlasnapure How exactly?

**Comment by rpedretti** [comment]
I also need it, please post the solution :)

**Comment by sandeshlasnapure** [comment]
Sorry for late reply. I have modified library as per my requirement long time ago.
please have a look at this modified lib but its old version I haven't modified it. 
you can find remove method by index or group for expandable group.
Please let me know if need any help.
 
https://expirebox.com/download/9fba4b1e4d51ffc1f5b93245672552f8.html
