### ISSUE TITLE
Add ExpandableGroup.setExpanded and reduce onToggleExpanded visibility

### ISSUE THREAD

**Issue by pzgz** [lisawray/groupie#108]
Per title, looks like the toggle states cannot be controlled through codes, is there a way to set the initial states? Thanks.

**Comment by pzgz** [comment]
Think I found a way, let's say `collapsed` is the flag indicates the group should be collapsed.

```
if (collapsed && expandableGroup.isExpanded()) {
    expandableGroup.onToggleExpanded();
}
```

Correct me if there's a better way.

**Comment by lisawray** [comment]
I'm not sure I'm a huge fan of adding it to the constructor.  Booleans always lead to such confusing constructor calls.  What do you think about just adding a `setExpanded(boolean)` method?

**Comment by lisawray** [comment]
I merged your PR, but I'm keeping this open because I'd like to also add a `setExpanded()` method in ExpandableGroup and make `onToggleExpanded` protected/private.  I think it's a clumsy API as is
