### ISSUE TITLE
Inefficiency due to lack of caching in Kotlin Android extensions

### ISSUE THREAD

**Issue by restor1** [lisawray/groupie#113]
Unlike the data-binding based version of groupie where view refernces will be cached,
it seems that referring to views from the generic view holder in 'bind' implementations
will simply result in calls to findViewById on each 'bind' execution.
more about this limitation:
https://proandroiddev.com/the-costs-of-kotlin-android-extensions-6809e2b32b13

Code from example app:
```java
open class CardItem @JvmOverloads constructor(@param:ColorInt private val colorRes: Int, var text: CharSequence? = "") : Item<ViewHolder>() {

    init {
        extras.put(INSET_TYPE_KEY, INSET)
    }

    override fun getLayout(): Int {
        return R.layout.item_card
    }

    override fun bind(viewHolder: ViewHolder, position: Int) {
        //viewBinding.getRoot().setBackgroundColor(colorRes);
        viewHolder.itemView.text.text = text
    }
}
```

and by converting to byte-code and back to java:
```java
public class CardItem extends Item {
   private final int colorRes;
   @Nullable
   private CharSequence text;

   public int getLayout() {
      return 2130968619;
   }

   public void bind(@NotNull ViewHolder viewHolder, int position) {
      Intrinsics.checkParameterIsNotNull(viewHolder, "viewHolder");
      ((TextView)viewHolder.itemView.findViewById(id.text)).setText(this.text);
   }
...
```

So, I wonder what can be done to keep the generic view holder approach 
while providing a solution that uses some sort of caching for views...

**Comment by digitalbuddha** [comment]
I think you should follow the pattern of implementation that Kotterknife uses

**Comment by restor1** [comment]
KotterKnife-like bindings are one possibility.
As part of 1.1.4 they added more flexibility to "Synthetic Properties":
[https://antonioleiva.com/kotlin-android-extensions/](url)
 This could be useful although still experimental.

**Comment by lisawray** [comment]
@restor1  -- You are totally right, I jumped the gun on adding Kotlin Android Extension support.  And thank you for pointing out this works correctly in 1.1.4.  For now, I'll note that if you wish to use this without any extra code, you should enable the experimental feature.

@digitalbuddha -- I'm roughly familiar with Kotterknife, but don't understand ... how can it help prevent writing any ViewHolder without Groupie including code generation?

**Comment by digitalbuddha** [comment]
It won't I misunderstood the implementation. 1.1.4 looks neat.

**Comment by lisawray** [comment]
Implemented here: https://github.com/lisawray/groupie/pull/125

I'll probably merge soon in order to cut a release, but 👀 appreciated!
