### ISSUE TITLE
After update to databinidng:2.0.0-alpha2 I get error converting bytecode to dex

### ISSUE THREAD

**Issue by IskuhiS** [lisawray/groupie#115]
I was using 1.0.0 version and  updated  
//    compile 'com.xwray:groupie:1.0.0'
    compile 'com.xwray:groupie-databinding:2.0.0-alpha2'

and receive this message
 Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/xwray/groupie/BuildConfig;

**Comment by lisawray** [comment]
Have you tried a clean and rebuild / invalidate caches?

**Comment by IskuhiS** [comment]
Sure.
