### ISSUE TITLE
How can I use UpdatingGroup with async/dynamic changing data?

### ISSUE THREAD

**Issue by aalexsanyan** [lisawray/groupie#116]
`for (int i = 0; i <sections.size(); i++) {
           sections.remove(section.getItem(i));
            }`

It nevers works ,I print before loop it prints 3 for items count and  after loop it prints the same amount

**Comment by lisawray** [comment]
What exactly are you trying to accomplish with this code?

Your variable `section` isn't defined in the code you posted.  Please post the entire, working snippet.
