### ISSUE TITLE
Sticky headers

### ISSUE THREAD

**Issue by Alex293** [lisawray/groupie#117]
Hi this lib is awesome ! The simplicity for managing multilevels items is impressive. For my project It's required that headers remain sticky on the top of the recycler. Is there a ways to achieve this or some pointer to do it ?

**Comment by bemusementpark** [comment]
Have you tried `CoordinatorLayout` and `AppBarLayout`?

**Comment by Alex293** [comment]
Sorry for the misunderstanding, I was talking about the header element of a expandable group. There are libs for this like : https://github.com/bgogetap/StickyHeaders. I was asking if you already did something like this. I'm gonna try to mix both libs and see the result but it would be nice to have this integrated into groupie.

**Comment by bemusementpark** [comment]
Oh Right, Sorry, I was thinking Quick Return.

To do that "correctly" you'd probably write your own `LayoutManager`, that's likely outside the scope of this `Adapter` library.

**Comment by lisawray** [comment]
Definitely out of scope for this lib!  You'll need a custom layout manager or item decoration or some other approach.  Good luck :)
