### ISSUE TITLE
Recyclerview is not scrolling smoothly and item background gets shuffled

### ISSUE THREAD

**Issue by andiakashd** [lisawray/groupie#121]
By using the BindableItem in kotlin

I am binding background as per the response but when I scroll recylerView, It lags and the Background image gets shuffled at other ItemRows.
Below is the whole scenario.
https://stackoverflow.com/q/46541929/5502638

**Comment by lisawray** [comment]
I replied on your StackOverflow post.  

Basically, you should use Picasso or Glide for image loading.  You have a few other errors, but I don't think they're causing the problem.  

Let me know if that clears things up!
