### ISSUE TITLE
Placeholder for GroupAdapter

### ISSUE THREAD

**Issue by ouattararomuald** [lisawray/groupie#127]
Hi !
In ```Section``` we have a **Placeholder** that is displayed when the section is empty.

Now If we have ```GroupAdapter``` in which all sections display the same type of data (like notes grouped by month) I think we need a **Placeholder at GroupAdapter level**. This way when all sections are empty we can display that Placeholder.

Actually, is there a way to observe the size and only the size of the adapter ?
I think I can observe the size with ```GroupDataObserver.onChanged()``` but in my app the ```RecyclerView``` will rarely be empty. So it can be expensive to call ```GroupAdapter.getItemCount()``` each time there is a change is a group.

My goal is to hide the ```RecyclerView``` when all sections are empty and display a placeholder.
Any suggestion ?

**Comment by lisawray** [comment]
Hey there!  Showing an empty state for the whole RecyclerView is a pretty common thing to do.  I didn't address it specifically in Groupie but the general approach is to call `myAdapter.registerDataSetObserver()` and like you said, check if the list is empty.  

Optimizing lookups and caching state (item counts) is a related goal.  I have an issue here: https://github.com/lisawray/groupie/issues/91.  PRs very welcome :)
