### ISSUE TITLE
Unable to use legacy viewholder

### ISSUE THREAD

**Issue by denimwho** [lisawray/groupie#128]
**My legacy viewholder**
```
class AppHolder extends RecyclerView.ViewHolder {
       AppHolder(View itemView) {
            super(itemView);
        }
}
```
When I use **AppHolder in Item<AppHolder>**, I get this error in Android Studio.
![appholder](https://user-images.githubusercontent.com/23311940/32178309-6a1c7690-bdb2-11e7-8736-6a354ce6202a.png)

If I **extend from ViewHolder of Groupie**, there is no error in Android Studio but there is **ClassCastException on runtime**.

_Library version_: 2.0.0-alpha2
_AS version_: 3.0.0

**Comment by lisawray** [comment]
Hm, I'll check it out tonight.  There shouldn't be an error in Android Studio, if so, that's bad!  

You will have to override `createViewHolder()` in your Item to return a new instance of your own ViewHolder.  Groupie doesn't create new ones with reflection or anything.  But that won't fix your original problem.  Let me get back to you soon.

**Comment by lisawray** [comment]
@denimwho, I was very sleepy earlier.  You'll have to change your existing viewholder slightly, to extend `com.xwray.groupie.ViewHolder`.

**Comment by denimwho** [comment]
Thanks. The above solution solved the issue.
