### ISSUE TITLE
Add support for RecyclerView States (Empty, Error, Loading, etc.)

### ISSUE THREAD

**Issue by kuuuurt** [lisawray/groupie#132]
Really love how this library removes boilerplate code from creating adapters. I've seen that we can have a Placeholder in the Section object but the placeholder can only depict that the list has no data or in an empty state. Would love it even more if this library would support multiple RecyclerView states!

Great job on this library!

**Comment by lisawray** [comment]
You're not the first person to ask for this.  In general, I think support for this is a low priority for this library, as the logic controlling screen state is often unrelated to the actual contents of the adapter, and desired UI varies widely.  

I've actually written what you're asking for on a previous project, like a `RecyclerViewFragment` which is a rough analogue of the old `ListFragment` (but with empty, error, loading, etc) and I think that's probably better suited to a different library altogether.  If you were to make one, you could use it in tandem with Groupie. :)

**Comment by kuuuurt** [comment]
That makes more sense. I always try to put the states in the `RecyclerView`'s Adapter but, yeah, you do have a point that it should just have the data or its contents. I'd try your suggestion out and maybe create a base fragment for the `RecyclerView` with the different states.

Thanks!
