### ISSUE TITLE
Equal spacing between items with fixed width.

### ISSUE THREAD

**Issue by yurabuloichik** [lisawray/groupie#143]
Question: how to achieve that? I.e: grid (width=340dp) with 3 items(width=each 100dp, not match_parent) in a row. So spacing are 10dp. If I set margin by myself to each item, some additional spacing added by GridLayoutManager(?) and they become not equal.
Thanks in advance.

**Comment by lisawray** [comment]
This doesn't have anything to do with Groupie, just RecyclerView / GridLayoutManager.  

Did you set your RecyclerView's width to 340dp? I suspect you let it be `match_parent`.

**Comment by yurabuloichik** [comment]
Asking that, cause in provided example spancount set to 12. But there are no rows with 12 items(amount depended on adapter's item), so I supposed that some behavior of this library based on this initial spanamount. If my decision is wrong, please close this issue.

**Comment by lisawray** [comment]
Not a problem to ask.  The example adapter uses a span count of 12 so it can create items that are 4, 3, and 2 across within the same RV (spanning 3, 4, and 6 columns).  

The example project also uses a custom item decoration to put even padding between the grid items, no matter how many there are.  You might find it useful: 
https://github.com/lisawray/groupie/blob/sdkLevels/example-shared/src/main/java/com/xwray/groupie/example/core/decoration/InsetItemDecoration.java

Hope that helps!
