### ISSUE TITLE
GroupAdapter.clear() calls group method with null parameter.

### ISSUE THREAD

**Issue by adrian5632** [lisawray/groupie#144]
Hi! It seems there's a wee bug in GroupAdapter.clear():

<pre>
public void clear() {
        for (Group group : groups) {
            group.registerGroupDataObserver(null);
        }
        groups.clear();
        notifyDataSetChanged();
    }</pre>

I believe it should call `group.unregisterGroupDataObserver(this);` since the first method expects `@NonNull` argument. Also this will cause an Exception when trying to add the same group after calling clear() since the observer hadn't been previously unregistered.

**Comment by adrian5632** [comment]
#146

**Comment by lisawray** [comment]
I've merged this fix and will try to put out a point release ASAP :)
