### ISSUE TITLE
Animation on Collapsing a Group

### ISSUE THREAD

**Issue by scottschmitz** [lisawray/groupie#145]
I am have been attempting to copy the example of an `ExpandableGroup` and I was wondering if the animation I am seeing is expected. The expand looks pretty smooth but the collapse is fairly awkward. My best guess is that it is caused by the Groups reporting a new count so when the adapter redraws with the notify call everything after the start temporarily disappears while the adapter recreates all of the available cells. Is this expected or might I be using the library in the wrong way? Thanks for any help or any suggestions!

![2018-01-06 17_45_20](https://user-images.githubusercontent.com/1085240/34644695-68e80938-f309-11e7-8f8a-5c1ef4da61a8.gif)

Higher quality version of the gif [available on gfycat.](https://gfycat.com/gifs/detail/HospitableTiredGuernseycow)

My code for creating the groups is pretty simple:
  
    regions
      .forEach { (group, regions) ->
        val groupItem = RegionGroupItem(group)
        ExpandableGroup(groupItem).apply {
          regions.forEach { region ->
            add(RegionItem(region))
          }
          adapter.add(this)
        }
      }

and then my bind simply calls the `onToggleExpanded` like in the example project.
    
    override fun bind(viewHolder: ViewHolder, position: Int) {
      ButterKnife.bind(this, viewHolder.itemView)
      name.text = group

      expandCollapse.setOnClickListener {
        expandableGroup.onToggleExpanded()
      }
    }

**Comment by alan-rodriguez** [comment]
Duplicate of #114

**Comment by lisawray** [comment]
I don't think this is a dupe of #114.  That issue is with the animation of children.  In this gif, I can see all the unrelated items below the expanding group disappear and reappear.  That's usually a hallmark of incorrect change notifications.  

Of course, since the change notifications are being sent by Groupie, this is a problem I would like to solve.  Thanks for the code, and I'll try to take a look soon!

**Comment by scottschmitz** [comment]
I've closed this issue because I cannot replicate this behavior myself. In my efforts to provide a sample project with the issue, I can no longer create the issue.  I suspect it was caused by the very awkward use of Butterknife above. The following works flawlessly.

I created a gist to my working fragment if anyone finds this and is looking for an example.
https://gist.github.com/scottschmitz/42f5b8858ff6f3240d6d4276c15c9bbc

**Comment by DamonBaker** [comment]
I have the same issue. In my case this would happen whenever my RecyclerView had its height set to wrap_content, or was inside a container with a height set to wrap_content. 

With wrap_content
![ezgif-3-df2b88c99e](https://user-images.githubusercontent.com/7334346/37505525-570f7424-2920-11e8-9dbb-f454ac706651.gif)

With match_parent
![ezgif-3-6c27ec1141](https://user-images.githubusercontent.com/7334346/37505659-e9e12d2e-2920-11e8-87fb-fdd96c0ad97e.gif)

Unfortunately in my case I would like to have my RecyclerView wrapped neatly inside a CardView and am not sure how to achieve this without using match_parent
