### ISSUE TITLE
Example for Kotlin in README not working

### ISSUE THREAD

**Issue by hardysim** [lisawray/groupie#147]
*This is basically a follow-up of #136 but as this is closed and we now have `groupie:2.0.0` I thought a new issue would be good.*

---

As mentioned in https://github.com/lisawray/groupie/issues/136#issuecomment-353358495 and my [demo-project](https://github.com/hardysim/groupie-demo) one **should include** `implementation 'com.xwray:groupie-kotlin-android-extensions:2.0.0'` when using kotlin. This is missing from `README.md`.

Plus, the item-classes need to extend from `com.xwray.groupie.kotlinandroidextensions.Item()` and *not* from `com.xwray.groupie.Item<ViewHolder>()`. Otherwise the view-imports via kotlin-android-extensions do not work (compare [`CarouselCardItem`](https://github.com/lisawray/groupie/blob/master/example/src/main/java/com/xwray/groupie/example/item/CarouselCardItem.kt) vs [`CardItem`](https://github.com/lisawray/groupie/blob/master/example/src/main/java/com/xwray/groupie/example/item/CardItem.kt) where only the latter seems correct).

Maybe the non-`kotlinandroidextensions`-version is used for java-compatibility? But when you want a kotlin-ish item, I suggest adding `groupie-kotlin-android-extensions` - which should be mentioned in `README.md` and not only in the example-project.

**Comment by Sloy** [comment]
Thanks for explaining the fix! ❤️ 
I can confirm that the described steps are enough and required to make it work :)

**Comment by lisawray** [comment]
Thanks very much for pointing this out.  I'll try and make the README clearer this evening!  

Writing documentation, harder than it looks :)
