### ISSUE TITLE
Extensions not working outside the sample

### ISSUE THREAD

**Issue by bernaferrari** [lisawray/groupie#156]
I am having a problem with kotlin extensions, might be related to this:
https://github.com/lisawray/groupie/issues/147
Or to something else. Basically, I extracted the sample app, simplified it a bit, and I can't run it, because viewholder.(...) finds nothing. Could someone please give a look? It looks Kotlin Extensions are fine, since I can run then on the mainActivity. The only place they aren't working is with the viewholders.
[testinggroupie.zip](https://github.com/lisawray/groupie/files/1647593/testinggroupie.zip)

**Comment by lisawray** [comment]
You need to enable Kotlin's experimental behavior in your build.gradle.  Put this at the top level of your build.gradle, same level as `android { ... }`:

```
androidExtensions {
    experimental = true
}
```

I don't have time to run it now but it certainly would NOT work without that, and everything else looks correct.

**Comment by bernaferrari** [comment]
Yeah!! This went **COMPLETELY unnoticed** by me, sorry and thanks for your fast support! I love this library!!!
