### ISSUE TITLE
the updating group item backgroud color is white, why not colorful?

### ISSUE THREAD

**Issue by nakemind** [lisawray/groupie#159]
![image](https://user-images.githubusercontent.com/19466502/35443345-b9bb16b6-02e5-11e8-8990-7b2af792abc6.png)

**Comment by seamus91g** [comment]
This is because line 33 in CardView.java is commented out. This sets the background color. 
```
 @Override public void bind(@NonNull ItemCardBinding viewBinding, int position) {
        //viewBinding.getRoot().setBackgroundColor(colorRes);
        viewBinding.text.setText(text);
    }
```

**Comment by lisawray** [comment]
I was using this example app to help me make animations for a speech and I used colors to highlight only the sections I was talking about at the time. I left them all commented out because it reminded me of the Material Design drawings this way.  :)
