### ISSUE TITLE
Item decoration removed when calling Section::update

### ISSUE THREAD

**Issue by mwttayler** [lisawray/groupie#172]
Hi, I'm experiencing an issue where calling Section::update seems to remove any existing item decoration applied before updating the list (please see gif below). 

Here's a link to a sample project I used to re-create the issue: https://github.com/mwttayler/android-groupie-item-decoration-issue

![ezgif-1-ca7c3b911a](https://user-images.githubusercontent.com/2511221/37295106-32a89a84-260f-11e8-96ea-f15deac32349.gif)

**Comment by mwttayler** [comment]
closing this, fixed by correctly overriding `getId`

**Comment by mwttayler** [comment]
Overriding `getId` seems to fix the jumping issue, but if I have an item that is shared between both tabs and I then try to call `notifyChanged` on that item (say in an on click listener) `bind` is not always called. 

![ezgif-2-67a1d201e9](https://user-images.githubusercontent.com/2511221/37302041-4c80c20c-2622-11e8-8960-ba587ef03c69.gif)

**Comment by lisawray** [comment]
Fascinating. I'll try to dig into this

**Comment by lisawray** [comment]
I no longer see your repo, so I'm closing this.  I'd have to see your ItemDecoration to see what's going on. It actually looks like when the items are being removed, a gray box the size of the full RV is drawn.  Please feel free to reopen.

**Comment by mwttayler** [comment]
My bad, deleted that repo a while ago.. I've created a new one, with a simpler example of this happening (you can use pull to refresh to replicate). 

https://github.com/mwttayler/android-decoration-example

**Comment by franvis** [comment]
Hello, have you been able to solve this issue? I'm running into the same problem :(
