### ISSUE TITLE
Is it possible to scroll to clicked item?

### ISSUE THREAD

**Issue by acolombo25** [lisawray/groupie#173]
I don't find a way to use RecyclerView's scrollToPosition(int position), as I can't find a way to reference the parent RecyclerView inside an Item, and I don't have any alternative ideas.

What I would like to do is to scroll to an Expandable Group when it collapses. Otherwise, in a long list of Expandable groups, when the last Expandable Group is toggled and collapses, it requires the user to scroll to see its content.

**Comment by hardysim** [comment]
I've tried this by passing the `position` in `bind()` of my `Item` to the activity which calls `recyclerView.smoothScrollToPosition(position+1)`.

This works, but only shows the first element after the header (so the user gets the idea that there's more content).

---

Better would be, to call `requestChildFocus()`, which reveals the whole view. But for this, we'd need a "container" view for the `ExpandableGroup`.

Is this possible?
I need this for an other issue as well, where I want to show the entire group as a card (looks like #247).
