### ISSUE TITLE
GroupAdapter.getAdapterPosition(Group group)) should probably return -1 if group is not found

### ISSUE THREAD

**Issue by TylerMcCraw** [lisawray/groupie#176]
It looks like `GroupAdapter`'s `getAdapterPosition(@NonNull Group group))` function returns 0 even if the group does not currently exist in `groups`.

This function should probably return -1 if the group passed in as a parameter is not found within `groups`.

By the way, I'm a huge fan of this library. Thank you so so much for making this open source.

**Comment by lisawray** [comment]
It totally should! Looks like an oversight.  I'll merge it into the next release

**Comment by TylerMcCraw** [comment]
Issue was fixed in PR #177
Gonna go ahead and close this one
