### ISSUE TITLE
Add position arg to onItemClickListener interface

### ISSUE THREAD

**Issue by MRezaNasirloo** [lisawray/groupie#178]
Since there is an access to the view position in the `com.xwray.groupie.ViewHolder` class why not passing it to `onItemClickListener` callback for convenience?
```java
private View.OnClickListener onClickListener = new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            // Discard click if the viewholder has been removed, but was still in the process of
            // animating its removal while clicked (unlikely, but technically possible)
            if (onItemClickListener != null && getAdapterPosition() != NO_POSITION) {
                onItemClickListener.onItemClick(getItem(), v, getAdapterPosition());// <=== pass the position here!!
            }
        }
    };
```

**Comment by MRezaNasirloo** [comment]
Right, what about passing the viewHolder instead?
And the bigger issue is how to get the adaptor position when a click listener is set on a portion of `viewHolder` not the `rootView` of viewholder?

**Comment by lisawray** [comment]
I consider the viewholder (at least ideally) to be an implementation detail.  But if you need to get it, it sounds like you want `RecyclerView.findViewHolderForAdapterPosition()`. (link)[https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html#findViewHolderForAdapterPosition(int)]

For implementing click listeners on a part of the view, not the whole view, I recommend passing a listener in the constructor of your Item which implements an interface.  The callback can pass the top level item.  e.g.:

```
class LikableItem(listener: OnLikeClickedListener): Item {
    override onBind(...) {
        viewholder.heart.setOnClickListener { listener.onLikeClicked(this@LikableItem) }
   }
}

interface OnLikeClickedListener {
   fun onLikeClicked(item: LikableItem)
}
```

From this callback, you can proceed to get the adapter position, if you need it.

**Comment by MRezaNasirloo** [comment]
This is exactly how I was doing it, but I'm looking for a better solution.
It would be nice if we had a method inside the `Item` class to override and set the click listeners on the parts we want, and receive the callbacks inside the `Item` class as well. I don't want the parent to know this information. This way I can use this Item anywhere I want.

**Comment by lisawray** [comment]
@MRezaNasirloo If you have a better idea, let me know!  

As far I can tell, the method you're looking for to set the click listeners is `bind()`.  ¯\_(ツ)_/¯

I'm not sure what information you don't want the parent class to know -- that the item requires a special click listener?  FYI, if you want to set the parent's default click listener (from `GroupAdapter.setOnClickListener()`) but not on the whole item, you can access it in an overload of `Item.bind()`:
```
override fun bind(holder: VH, position: Int, payloads: List<Object>, onItemClickListener: OnItemClickListener, onItemLongClickListener: OnItemLongClickListener) {
    // don't forget to call super though!
}
