### ISSUE TITLE
Scroll to a certain Item in RecyclerView

### ISSUE THREAD

**Issue by alvin-nt** [lisawray/groupie#182]
By following your example, I managed to create some expandable list, using `RowHeader extends ExpandableItem` and `RowItem extends Item`.

I am using `Section` to wrap every `ExpandableGroup(RowHeader)`

Let's say I have all references of the header in a `Map`, and I want to be able to scroll the `recyclerView` to a particular `RowHeader`.

My questions:

1. Is it better to store the `ExpandableGroup` or the `RowHeader` reference in the map?
2. How to scroll the `RecyclerView` to a particular `RowHeader`?

**Comment by lisawray** [comment]
You can hold a reference to either -- whatever you prefer!

If you hold a reference to the group, you can call:
```
val position = GroupAdapter.getAdapterPosition(group)
```

If you hold a reference to the header, you can call
```
val position = GroupAdapter.getAdapterPosition(item)
```

In either case, you can just use the position to scroll:
```
RecyclerView.smoothScrollToPosition(position)
```

**Comment by rup4kt43** [comment]
@lisawray  can you help me on how to get the reference of the group ,I am facing some difficulties.

**Comment by Zhuinden** [comment]
You need to scroll to the position of the item 🤔
