### ISSUE TITLE
Update Kotlin extensions integration

### ISSUE THREAD

**Issue by n-belokopytov** [lisawray/groupie#186]
We have had troubles with Kotlin extensions integration of your lib. Unfortunately some of the code that you have written is using a deprecated version of Kotlin's stdlib and it random compilation errors for us with no particular stacktrace.

**Comment by lisawray** [comment]
I've just published groupie 2.1.0.  It's now using Kotlin 1.2.41.  Would love if you can give it another spin!

**Comment by lisawray** [comment]
Closing for now because we're on the latest Kotlin ... please reopen if you have any further issues. :)

**Comment by n-belokopytov** [comment]
Thanks for taking care of this! We ended up using synthetics generated by Kotlin's own Android extensions without too much overhead, by extending a viewholder with a template parameter and by referencing layout elements through the "root" reference to the coresponding view.
