### ISSUE TITLE
updateAsync (2.2.0-alpha1) won't propagate errors

### ISSUE THREAD

**Issue by lisawray** [lisawray/groupie#190]
Current implementation using AsyncTask will just swallow errors.  

Maybe something like: https://stackoverflow.com/questions/1739515/asynctask-and-error-handling-on-android/6312491#6312491

**Comment by PaulWoitaschek** [comment]
Or directly use [ListAdapter](https://developer.android.com/reference/android/support/v7/recyclerview/extensions/ListAdapter)?

**Comment by lisawray** [comment]
@PaulWoitaschek , I'd love to use ListAdapter, but there's a couple problems ...

- ListAdapter needs a flat list of Items to diff.  In order to get there from a `List<Group>`, we'd have to first flatten the group structure, *then* diff.  Flattening also needs to be off the main thread -- so we don't escape writing this stupid AsyncTask (or whatever)
- Groupie is currently tightly coupled with the adapter. This is a design flaw I'd like to fix in the next major release. 

The issue with exceptions is fixed in https://github.com/lisawray/groupie/releases/tag/2.3.
