### ISSUE TITLE
[Question] Suggestion on switching state (normal <-> editing/selection) for the adapter

### ISSUE THREAD

**Issue by khatv911** [lisawray/groupie#193]
I'm having a request to apply selection/editing for the adapter. 
Currently my approach is to attach the state with the model, and call update/notifyChange. Anyone out there has better solution? Say, make the adapter stateful instead of the model? Appreciate any help.

**Comment by lisawray** [comment]
That's how I've always handled it (state in model).  

My take on this lately is that I send callbacks from user actions to my ViewModel (the Architecture Components one).  Then it dispatches a new list of Groups to the view via Rx or LiveData.  In the view, I use `GroupAdapter.update(List<Group>)` or `updateAsync()` to diff them and send out the minimal set of required `notifyChangeXX()`.
