### ISSUE TITLE
Groupie resets all item state when recyclerview is scrolled up

### ISSUE THREAD

**Issue by cerberusv2px** [lisawray/groupie#196]
I have a groupie model with a boolean variable which is false by default.
Suppose the variable is set to true.
Now if i scroll the recyclerview, the variable is again set to false.

**Comment by khatv911** [comment]
can you give a link to your repo?

**Comment by lisawray** [comment]
Groupie doesn't mutate Items or Groups.  

If you're seeing something in your views toggled after scrolling, the usual culprit is something like making a change to a view only when `myBool` is true.  e.g.:

```
   @Override void bind( ....) {
        if (myBool == true) holder.view.background == Color.GREEN;
   }
```

This means that the view's background can be an unexpected color after viewholder reuse. The solution is to handle all possible cases (true and false for booleans, all cases of enums, etc) in your bind method.
