### ISSUE TITLE
Livedata support?

### ISSUE THREAD

**Issue by jayasio** [lisawray/groupie#203]
Grouping Items from Livedata<List<Item>> by one particular field (ie. date)? Not sure if it's an issue :|

**Comment by takahirom** [comment]
In relation to the architecture component, if the item of Groupie implements LifecycleOwner, items can be changed from ViewModel and so on, so it can be used in various ways.

**Comment by lisawray** [comment]
I don't use LiveData, but I'm not against supporting it :)  

That said, it looks like you want some kind of [Transformation](https://developer.android.com/reference/android/arch/lifecycle/Transformations) to change, say, `List<Book>` to `List<Group>`.

**Comment by MrLogic85** [comment]
I use Groupie with LiveData without problem, do not confuse concepts. Groupie is a RecyclerView Adapter.

A primitive way of doing it could be like this.
```
val groups: LiveData<List<Group>>
val observer = Observer<List<Group>> { groups ->
    groupAdapter.update(groups)
}
```
