### ISSUE TITLE
Androidx support?

### ISSUE THREAD

**Issue by ovitrif** [lisawray/groupie#207]
Is a migration to androidx libraries planned?

Right now I can't build if I replace support libraries with the new androidx :)

If not, I may be doing a PR 👍

**Comment by bernaferrari** [comment]
It is now stable @lisawray 
https://developer.android.com/topic/libraries/support-library/androidx-rn

**Comment by digitalbuddha** [comment]
Is there a reason jetifier won't work?

**Comment by bernaferrari** [comment]
Yes, I don't know why, but the viewholder doesn't work.

**Comment by shadowsheep1** [comment]
> Is a migration to androidx libraries planned?
> 
> Right now I can't build if I replace support libraries with the new androidx :)
> 
> If not, I may be doing a PR 👍

I just installed AS 3.2 from stable channel and do a Refactor -> migrate to AndroidX. Got no problem.

I use Java and not Kotlin and version 2.1.0 of groupie library

**Comment by TimoPtr** [comment]
I open a PR https://github.com/lisawray/groupie/pull/212

**Comment by lisawray** [comment]
Androidx support is merged!  Just trying to figure out our publishing situation.  novoda-bintray-plugin has a bug with Gradle 5.0 so I may have to migrate us to another publishing solution.  Hang tight :)
