### ISSUE TITLE
Repo dead?

### ISSUE THREAD

**Issue by jordond** [lisawray/groupie#211]
No contributions, plenty of open issues, and unanswered PR's.  Perhaps it's time to add another maintainer?

#207 is currently holding me up, as I'm sure others are too.

I don't really have the bandwidth to fork it myself, maybe someone else can?  I really don't feel like refactoring my codebase to switch to a groupie alternative.

Thoughts?

**Comment by ovitrif** [comment]
I also believe Groupie as a concept is a top choice for professional android development, for this reason I might think about maintaining it myself :)

Quite clear it would be more or less the same as here with only one contributor, so if there is another volunteer I think we can form a team and keeping this awesome solution alive for the upcoming times :)

Any volunteers to do this together?

**Comment by lisawray** [comment]
Hi guys. I'm a jerk for letting this go so long.  But I'm on it now.  I'm going to spend a couple hours getting the project back to stable and will publish a new alpha this weekend.  

I don't want to drop the ball like this again, so I'm very open to the idea of adding contributors.

**Comment by bernaferrari** [comment]
Lisa!!! Nice to hear you again!!! Hope to see you using Groupie internally on Facebook (instead of Litho :P)!!

**Comment by lisawray** [comment]
Haha!  That won't happen.  But maybe we can sneak some good ideas from
Litho into Groupie.

>

**Comment by lisawray** [comment]
All right ... we're back!
