### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by fawaad** [lisawray/groupie#217]
Unsure if there are plans to add AndroidX support. I haven't seen anything like that and wondered if anything was in the works.

**Comment by fawaad** [comment]
Taking it back. I was looking at an older version of the library. Thanks!

**Comment by fawaad** [comment]
I see that this is in the works. Please let me know if there is something I can do to help

**Comment by lisawray** [comment]
Done in v2.2

**Comment by deep7964** [comment]
How to update from 2.1.0 to 2.3.0 without migrating the whole project to androidX
