### ISSUE TITLE
Manifest merger failed (AndroidX)

### ISSUE THREAD

**Issue by ghost** [lisawray/groupie#221]
Noticed when updating to v2.2 I get Manifest merger issue: 

`Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0-rc01] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).`

Does this mean to use the latest version we will need to migrate our projects to use AndroidX ?

**Comment by Anavrin1990** [comment]
> Noticed when updating to v2.2 I get Manifest merger issue:
> 
> `Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0-rc01] AndroidManifest.xml:22:18-91 is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).`
> 
> Does this mean to use the latest version we will need to migrate our projects to use AndroidX ?

The same problem. Waiting for an answer =)

**Comment by jordond** [comment]
I can tell you that yes, updating to AndroidX will resolve this error.  If that's not something you can do in your project, then you'll have to stay at a lower version.

**Comment by Anavrin1990** [comment]
> I can tell you that yes, updating to AndroidX will resolve this error. If that's not something you can do in your project, then you'll have to stay at a lower version.

Thank you! The update solved the problem =)
