### ISSUE TITLE
bind() not called after notifyChanged() when using update() instead of add()

### ISSUE THREAD

**Issue by hardysim** [lisawray/groupie#223]
I'm using `notifyChanged()` on an `Item` to trigger a redraw via `bind()` (e.g. selecting an element via long-press and change its background to represent the "selected"-state).

This is working fine, when I add the elements via `groupAdapter.add()`.

But when changing this to `groupAdapter.updateAsync()` (I want to take advantage of diffing to get the nice animations when altering the list), `bind()` is no longer called.

Is this intended? Am I missing something?

**Comment by lisawray** [comment]
The short answer is, you can't.  

I intentionally disabled this functionality for async updates. Mixing asynchronous updates through `updateAsync()` and any other type of update means the adapter's state can become inconsistent.  For example, if you start `updateAsync()`, then call `notifyChanged()` on an Item (say the user selected it so Item.selected = true), THEN your async changes land, 
1) your adapter's content list will be replaced, meaning the Item model will be overwritten with a non-selected one
2) the item view will remain selected briefly, but the next time it's bound it will unselect itself
3) the reference you hold to the selected Item is probably now pointing to the *old* item.  

Asynchronous updates really only work with a one-way data flow.

**Comment by lisawray** [comment]
Related: https://github.com/lisawray/groupie/issues/189
