### ISSUE TITLE
Gets Manifest Error

### ISSUE THREAD

**Issue by amjadz** [lisawray/groupie#233]
Hello there,

When ever I am i try to install the library, the issue is that i keep getting this error:
`Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-33:19 to override.`

I am wondering why this happens, and when I do override the appComponentFactory it still doesn't work.

**Comment by sutejoramadhan** [comment]
try to add 
tools:replace="android:appComponentFactory"
android:appComponentFactory="whateverString"
to your application section in the manifest.

**Comment by lisawray** [comment]
Is your app updated to androidx?  The latest version of groupie requires androidx.  

You can use 2.1 or earlier to use the standard Android support lib.

**Comment by amjadz** [comment]
I had no idea i had to migrate to androidx, that solved the issue! Thank you for your help!
