### ISSUE TITLE
Incompatible Groupie Adapter

### ISSUE THREAD

**Issue by AkaraHexels** [lisawray/groupie#236]
Hi, first of all, I apoligize in case if this is not the place to ask these sort of questions, but I've been searching and searching and I just can't find the answer.

I'm learning Android development, while following a tutorial made by Lets Build this App ( on Youtube ). 
He used this library and I tried too, but I'm failing. I created a RecyclerView and tried to make a GroupAdapter using Groupie like this:
```        val groupAdapter = GroupAdapter<ViewHolder>()
        newmessage_view.adapter = groupAdapter
```

This is what he does in the video, but when I do it, it gives me an error:

> Type mismatch.
> Required:
> (RecyclerView.Adapter<android.support.v7.widget.RecyclerView.ViewHolder!>?..RecyclerView.Adapter<*>?)
> Found:
> GroupAdapter<com.xwray.groupie.ViewHolder>

Again, I'm sorry if this is not the place, but I hope someone can help me. Thanks in advance.

**Comment by MrLogic85** [comment]
Try on GitHub instead, seems like a more basic problem than how to use a library

**Comment by MrLogic85** [comment]
Sorry, typo, try on stackoverflow

**Comment by AkaraHexels** [comment]
@MrLogic85 Alright. Will do. Thank you for your time to respond.

**Comment by lisawray** [comment]
I thought I wrote a response to this ... don't know what happened!

You need to use the new versions of the Android support library, under the androidx package name.  The latest version of Groupie that supports the old ones is 2.1.  But if you're just starting out with a new project, I strongly recommend you start with the newest support libs.  Android Studio > New Project should have your back here!

**Comment by jholw** [comment]
Pessoal boa noite, preciso de ajuda o que posso fazer para usar o groupie no androidx 3.4.1 com gradle 5.4.1, ele nao aceita a implementação na gradle.biulder do app.  Alguem pode me ajudar?

**Comment by sapuglha** [comment]
[pt-BR]
> Pessoal boa noite, preciso de ajuda o que posso fazer para usar o groupie no androidx 3.4.1 com gradle 5.4.1, ele nao aceita a implementação na gradle.biulder do app. Alguem pode me ajudar?

Hey @jholw nem todo mundo fala Português aqui. Eu uso Groupie com Android Studio 3.4.1 e Gradle 5.4.1 sem problemas. Postar uma nova questão com exemplo demonstrando o problema ajuda bastante, apesar de que esse tipo de pergunta seria feita no StackOverflow primeiro.

[en]
Q: Good night folks, I need help what can I do to use groupie with androidx 3.4.1 with Gradle 5.4.1, it does not accept the implementation on gradle.builder on app. Could anyone help me?
A: Hey @jholw not everyone speak Portuguese here. I'm using Groupie with Android Studio 3.4.1 and Gradle 5.4.1, no problem. Adding a new question with an example demonstrating the problem helps us understand, although this kind of question would be posted on StackOverflow first.

**Comment by jholw** [comment]
Hello @sapuglha  good night sorry I just forgot, lol.
I managed after restarting my android studio I was able to run the Groupie implementation. Hugs.

**Comment by AmanGr** [comment]
Anybody found a solution to this error?

**Comment by Zhuinden** [comment]
I believe you need to use AndroidX, not android.support.v7

**Comment by jholw** [comment]
Hello all right, so how long ago I'm not reminded anymore of the error, but
it was even a matter of used the androidx, after fixing the use he
accepted. Although I had to start my project over.

Thank you. Hugs.

Em qua., 14 de jul. de 2021 às 08:15, Gabor Varadi ***@***.***>
escreveu:
