### ISSUE TITLE
Question: why are you using notifyItemRangeRemoved instead of notifyItemRemoved

### ISSUE THREAD

**Issue by Ajimi** [lisawray/groupie#238]
As I'm using this awesome 👍 Library in my projects. I thought that I need to dive deep in your code and see the mysterious part that runs this library. While I'm walking through your code-base and trying to understand what happens exactly when you add or remove a single group from the adapter. 
I found out that you are using `notifyItemRangeRemoved`. I'm curious if there's a specific reason why you are not using `notifyItemRemoved(position) ` .
```java
private void remove(int position, @NonNull Group group) {
        int itemCountBeforeGroup = getItemCountBeforeGroup(position);
        group.unregisterGroupDataObserver(this);
        groups.remove(position);
        // notifyItemRangeRemoved(itemCountBeforeGroup, group.getItemCount());
       notifyItemRemoved(position); // this line is added by me
}
```
the code above is taken from `GroupAdapter` class , as you can see I commented the last line and added my implementation..

My Question : 

- Does this have any affect ? 
- And why you have chosen `notifyItemRangeRemoved(int,int) `instead of `notifyItemRemoved(int)`

**Comment by wbinarytree** [comment]
I guess a group is not necessarily item . It can be serial items for example an expanded expandable group.
