### ISSUE TITLE
Horizontal column

### ISSUE THREAD

**Issue by douglasalipio** [lisawray/groupie#244]
Is possible to have a horizontal column? 

1  2
3  4
5  6
7

Not like the [sample](https://github.com/lisawray/groupie/blob/b767c41a2442be0ea88ae092779e3b69d8de891f/example/src/main/java/com/xwray/groupie/example/MainActivity.kt#L166):

1  5
2  6
3  7
4

**Comment by lisawray** [comment]
Yeah, absolutely!  This is the default behavior of items in a RecyclerView
with a GridLayoutManager actually.  Add your items to any group or directly
to the adapter.  Just make sure they're half the layout span of your whole
RV.

**Comment by douglasalipio** [comment]
That's right, I was creating a `ColumnGroup`. I just add the `group` to the adapter directly as you said. Thanks :dancer:
