### ISSUE TITLE
There is no notifyDataSetChanged() function in GroupAdapter

### ISSUE THREAD

**Issue by emiraslan** [lisawray/groupie#262]
Version: 2.3.0

I can't update my `recyclerView` when my dataset is changed. 
This is how I build adapter and assign it to `recyclerView`:
``` kotlin
    val adapter = GroupAdapter<ViewHolder>()
    Statics.buyers.forEach { buyer ->
        adapter.add(BuyerListItem(buyer))
    }
    rootView.buyersRecyclerView.adapter = adapter
```

So, when I add new buyers to `Statics.buyers` list, I couldn't find any function to update the `recyclerView` accordingly. Should I create a new adapter and reassign all the items every time I want to update the `recyclerView`. What do you recommend?

**Comment by kodaman2** [comment]
Have you tried using update function? Have a look in [Section.java](https://github.com/lisawray/groupie/blob/981f626216b5f55dbb3365c0aad775e84118923c/library/src/main/java/com/xwray/groupie/Section.java#L129)

**Comment by emiraslan** [comment]
Thank you!
