### ISSUE TITLE
Groupie isn't correctly diffing my Kotlin data classes.

### ISSUE THREAD

**Issue by adawoud** [lisawray/groupie#266]
I expect Groupie to not show any new items if I refresh and get the same data from the database, but this isn't what's happening. Every time I perform a pull-to-refresh, groupie adds the same items to the RecyclerView again.

What am I doing wrong? Also,unrelated, but is the way I'm using Picasso here right?

Here's my data class:

    data class BookItem(
        val id: String,
        val name: String,
        val author: String,
        val publishDate: Int,
        val coverImageUrl: String
    ) : Item() {

    override fun getLayout() = R.layout.item_book_list

    override fun bind(viewHolder: ViewHolder, position: Int) {
        Picasso.get()
            .load("https://source.unsplash.com/random")
            .into(viewHolder.coverImageView)
        viewHolder.titleTextView.text = name
        viewHolder.authorTextView.text = author
        }
    }

And the way I'm adding these items to the RecyclerView is following the docs for adding a Section.

Thanks!

**Comment by ayonymus** [comment]
Under the hood the `Secion.update` function is using the 'isSameAs(other: Item)' method for comparing two items, which is using the layout and the `long id` field of the `Item` class.

Your `BookItem` has `id: String`, which is not used for equality.

Solution could be for you to either use a long for id if applicable and call `Item(id)` constructor or override the `isSameAs` method.
