### ISSUE TITLE
Did it support check box actions in viewholder?

### ISSUE THREAD

**Issue by kaviyarasu1987** [lisawray/groupie#284]
I have implemented groupie using custom view which has checkbox on it but it is getting unchecked whenever scroll down and come back to first view holder

I have tried to use on bind on check listener and change the status based on check but its still acting the same please help/advise

**Comment by kaviyarasu1987** [comment]
i dont think i should required to update in Adapter

**Comment by khatv911** [comment]
either keep the checked in the model attach with the item , or in an Map or Set. set the check state again in onBind
This has nothing to do with groupie.

**Comment by khatv911** [comment]
@ValCanBuild  I guess we can close this one.
