### ISSUE TITLE
Updating Groups/Items in the GroupAdapter in-place

### ISSUE THREAD

**Issue by jestontzh** [lisawray/groupie#304]
Hi,

Currently i've been updating specific data in my adapter by:
1) Removing it at the index
2) Modifying the data
3) Adding it back in at the same index

GroupAdapter.update() doesn't really serve my purpose since my data can be quite large. Any ideas on how I can do the above better? Maybe I've missed something.

Thanks!

**Comment by lisawray** [comment]
Are you talking about changing a single item?  You can modify the Item itself and call `Item.notifyChanged()` or `Item.notifyChanged(payload)`.  Then you'll receive a call to `Item.bind(Viewholder ...)` and you can perform updates to the view there.

**Comment by jestontzh** [comment]
Yes, that and also adding to an ExpandableGroup. 

I've figured out the latter and I'll follow up on your suggestion. 

Thank you!

**Comment by Andre-max** [comment]
Using `Item.notifyChanged()` changes adapter's data but doesn't update the UI (the recyclerview does not change). Any solution?
