### ISSUE TITLE
Disable auto scroll after placeholder

### ISSUE THREAD

**Issue by logan23** [lisawray/groupie#338]
Hi.
I have an issue when I use a placeholder. 
When I set data to section, recycler view auto-scroll to last position. It is possible to disable this behavior?
```kotlin
val section = Section()
section.setPlaceholder(EmptyItem())
groupAdapter.add(section)
```
```kotlin
fun setData(items: List<MyItems>) {
   section.update(items)
}
```

**Comment by Glurt** [comment]
I don't think this is related to Groupie as you can find people having similar issues using Epoxy and regular `RecyclerView.Adapter`, so it seems related to DiffUtil.

This thread has some good examples of fixing this issue
https://github.com/airbnb/epoxy/issues/224

**Comment by Zhuinden** [comment]
Hacky but worth considering: https://stackoverflow.com/a/44053550/2413303
