### ISSUE TITLE
ViewBinding: implementations should not require getLayout method.

### ISSUE THREAD

**Issue by tylerwilson** [lisawray/groupie#340]
**Describe the bug**
In the new ViewBinding version of BindableItem (thank you btw), there is no more need for resource IDs - you only need the ViewBinding derived class. So BindableItem implementations should not need to override the getLayout method. 

**To Reproduce**

Create a new derived class from BindableItem<ViewBinding> like so:

`class ProductQuantityItem(val item: Product.Quantity): BindableItem<ViewProductDetailItemBinding>() {
}`

if you do not implement the getLayout: Int method, you will get an error 'does not implement getLayout'.

**Expected behavior**

I would expect the BindableItem<ViewBinding> to overload getLayout and do nothing / return 0.

**Library version**
2.8.0

**Additional context**

**Comment by tylerwilson** [comment]
Okay, I did some more research in the code, and at the moment I am wrong. It would take an adjustment inside the GroupAdapter to do this, and even then it may not be a simple matter.

So I will close this myself...

**Comment by chriswiesner** [comment]
can't we leverage the Binding class to know which layout is used?
also the override for `initializeViewBinding()` could be ommited as we know the type already.
this feels currently quite cumbersome to use.

**Comment by Zhuinden** [comment]
Layout ID is used as the default view type ID.

Binding class doesn't tell you what layout id it uses. 

The override is unavoidable because the invocation is to a static method.
