### ISSUE TITLE
Multiple item selection

### ISSUE THREAD

**Issue by davisoqt** [lisawray/groupie#344]
Hi, how can i handle recyclerview multiple ítem selection with groupie?

**Comment by Zhuinden** [comment]
Generally you need to track the selection state yourself, in simple cases it can be as simple as giving `isSelected: Boolean` to an `item`, in that case you generally set the items with the updated flag, when one item changes - but you can also use the `notifyItemChanged` + payloads approach that is also used in the example for the "favorite" selection - it's very similar in principle.
