### ISSUE TITLE
can you add overscroll effect?

### ISSUE THREAD

**Issue by hxmwr** [lisawray/groupie#348]
**Is your feature request related to a problem? Please describe**
Often we need refresh page by pulling down the whole page like the effect in IOS.

**Describe the solution you'd like**
When the page reach the top, if continuing to pull down the page then allow the whole page to overscroll just like the page is hanged on a spring, and show some loading icon in the overscroll-generated gap. Since you've already support some in-recyclerview item animations, so this overscroll effect will also meet the library's design purpose.

**Additional context**

**Comment by Zhuinden** [comment]
You can achieve this by attaching an item decoration to the RecyclerView, Groupie only manages the adapter.

Therefore, Groupie already works with any libraries that provide such "spring-like behavior": https://github.com/EverythingMe/overscroll-decor

The "pull to refresh" could be done with SwipeRefreshLayout wrapping the RecyclerView.

Either way, not a Groupie responsibility.
