### ISSUE TITLE
How to work on native keyboard overlaps the fields using groupie?

### ISSUE THREAD

**Issue by ronjunevaldoz** [lisawray/groupie#356]
I need to show keyboard below the textfields

**Comment by Zhuinden** [comment]
That is a matter of using a RecyclerView as the match_parent view of the layout, and using `adjustResize`.

Keyboard is not specifically related to how either Groupie or RecyclerViews are managed, however, so technically it'd be the same either way. Softkeyboard is always pain, though, so hopefully you managed to resolve this issue.
