### ISSUE TITLE
How to wrap BindableItems into CardView ?

### ISSUE THREAD

**Issue by lpancevski** [lisawray/groupie#360]
Is there a way to wrap BindableItems in CardView ?
Something similar like this on the picture

![Groupnew](https://user-images.githubusercontent.com/5330561/92141492-cd55dd80-ee12-11ea-9bc3-e79c3808f8a0.png)

**Comment by Skyyo** [comment]
This isn't related to the library, thus should be closed.
1) Create an item that has <CardView as it's root, and 1/2 textviews.
2) You can use **RV Item Decorator** to adjust the top/bottom cardView radius. Or manually set radius to each items <CardView.
The same approach would apply for the regular RV adapter anyway @lpancevski

**Comment by Zhuinden** [comment]
The trick is that if these are all "lists in a card", then you could theoretically use nested RecyclerViews, but I'd expect making the internal one be `nestedScrollingEnabled=false` to not have scrollability, and instead stretch to max and wrap_content.

So non-recycled internal cards. That way, the external card can be one item.

You most likely wouldn't be able to use 1 RecyclerView for the whole thing unless you do black magic with decorators, but that's beyond scope of this issue.
