### ISSUE TITLE
How to pass String UUID to Item::getId?

### ISSUE THREAD

**Issue by bigman212** [lisawray/groupie#361]
I generate **UUID** for each new record in SQLite database via Room. 
These UUIDs are stored as **String** and I want to pass String UUID as id for RecyclerView Groupie Item. The problem is - Item::getId wants only **Long**.

For example:
```kotlin

data class Note(@PrimaryKey val id: String){ 
  companion object {
    fun createNew(): Note {
      val uuid = UUID.randomUUID().toString()
      return Note(uuid)
    }
  }


class NoteListItem(private val noteToBind: Note) : BindableItem<RvNotesItemBinding>() {
  override fun getId(): Long {
    return noteToBind.id // compilation error: id is generated UUID with type of String
  } 
...
}
```

Any ideas how to implement this use case? Or it would be better if I switch to id stored as Long in Room?

**Comment by bigman212** [comment]
Sorry for disturbing - I've found solution.

```kotlin
  override fun getId(): Long {
    return UUID.fromString(itemToBind.note.id).mostSignificantBits and Long.MAX_VALUE
  }
```

**Comment by bigman212** [comment]
Here I go again.
Can we somehow use String ids (for example "orunST313u") to pass to Item::getId?

**Comment by Zhuinden** [comment]
Unfortunately, `getItemId` comes from `RecyclerView.Adapter`, which means `getItem().getId()` is just a means to delegate this adapter method call over.

https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter#getItemId(int)

I've been using `stringId.hashCode()` for it and hope for the best, but it's worked so far.
