### ISSUE TITLE
How to implement Groupie inside the Fragment?

### ISSUE THREAD

**Issue by TheBukharian** [lisawray/groupie#363]
Im getting error: "adapter shouldn`t be null" when i use Groupie adapter inside fragment class.

**Comment by coolerinc** [comment]
@TheBukharian try to set adapter onActivityCreated
```
override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        recyclerview.apply {
            adapter = groupAdapter
        }
    }
```

**Comment by Zhuinden** [comment]
Technically, `onViewCreated` is more appropriate, because `onActivityCreated` is scheduled for deprecation in `fragments-1.3.0`.
