### ISSUE TITLE
Add a new method that updates a single item in a GroupAdapter

### ISSUE THREAD

**Issue by Andre-max** [lisawray/groupie#364]
**Is your feature request related to a problem**
Yes. I have an app where the user can like an item in a recycler view. Problem is that whenever that happens, I have to call adapter.update() which updates the whole list and really spoils the UX.

**Describe the solution you'd like**
A new method, for example adapter.updateItem,
that updates a single item in a list.

**Comment by Braxeo** [comment]
You need to keep reference to the item that you're updating and call
`item.notifyChanged()` or `item.notifyChanged(payload)`

Inside your implementation of the Item make sure to override 

```
override fun bind(viewHolder: ViewHolder, position: Int, payloads: MutableList<Any>) {
        super.bind(viewHolder, position, payloads)
    }
```

Otherwise you can allow the adapter to figure out the changes by overriding 

    override fun isSameAs(other: Item<*>?): Boolean {
        return super.isSameAs(other)
    }

    override fun equals(other: Any?): Boolean {
        return super.equals(other)
    }

    override fun hashCode(): Int {
        return super.hashCode()
    }

**Comment by Andre-max** [comment]
Thanks @Braxeo
