### ISSUE TITLE
Highlight an item in the list

### ISSUE THREAD

**Issue by thiruandroidhub** [lisawray/groupie#368]
Hi,

I have implemented a list with Section containing nested groups. Which is list of groups contain items. The section has header and body where the body will be list of items and the header will be another item. If i want to highlight the items inside the headers what is the best way to do it? 

I have followed your example of update with payload but i want to unhighlight an item which was highlighted before when another item is currently highlighted, so that only one will be ever highlighted at a time.

I have tried to store state in the adapter with the previous item to unhighlight when the current one is highlighted with something like this: but it doesn't always work to highlight the current one if items are added or deleted in between groups.

```
private fun highlightItem(item: PriceAlertChildItem) {
        previousItem?.notifyChanged("")
        previousItem = item
        item.notifyChanged(HIGHLIGHT)
    }
```

Could you please help?

**Comment by Zhuinden** [comment]
Hey hey!

I'd love to help, but I don't know enough about your items, and I'm especially more curious about how you ensure that the selection state of which item is highlighted is preserved across configuration changes / process death.

Do you by any chance have a slightly more detailed example?

Thank you :slightly_smiling_face:

**Comment by thiruandroidhub** [comment]
Sorry for the late reply got busy with other things :-)

In the mean time I have figured out the solution for the issue i had and all good here.

The issue was we have our own `GroupAdapter` implementation (so that we can provide our own diff calculation) for efficiency. Now when there are many groups with items, i couldn't call `notifyChanged` on an item which is in the group that is not recently changed with any item changed updates.

The `bind` is never called in this case to update the UI to highlight it. It works only to highlight the items in the same group after there is a change on any item in that same group.

In order to make this to work i have implemented a fun to highlight that is directly called on the Item itself without relying on the notifyChanged made it to work.

To answer your question regarding how we preserve the state on config changes - we don't do that at present. 

We simply start fresh on the UI as the views are recreated so that the adapter too. If we want, we can provide a viewModel to save state to survive a config changes to show if any selected which we can do if there is a requirement for it :-)

Thanks. 👍

**Comment by Zhuinden** [comment]
Ah okay, glad to hear the issue is resolved 🎉
