### ISSUE TITLE
Update/replace Section items silently (without DiffUtil and notify-callbacks)

### ISSUE THREAD

**Issue by vkay94** [lisawray/groupie#369]
>**Is your feature request related to a problem? Please describe**
A clear and concise description of what the problem is.

Currently, the only way to change the items of a `Section`  with a complete new list is by calling `clear`+`addAll` or `update`. Both methods trigger `notifyItemRangeRemoved` and `notifyItemRangeInserted` sequentially (when an own `DiffResult` which returns `false` for `areContentsTheSame` and `areItemsTheSame` is passed to `update`).

Consequently, the `RecyclerView.ItemAnimator` won't run `animateChange(...)` which is the only method to access the old and new `ViewHolder` and gives a decent fade animation when the whole list changes/is reordered (looks better in my opinion than moving items everywhere). 

The only way to update the whole 'Section' is to call `notifyChanged()` but you can't update the order of them silently (the `children`).

This behavior can be seen in the YouTube app when you open a personal playlist and change the order type. The items are fading pretty fancy :D

>**Describe the solution you'd like**

I think it would be nice to give the opportunity to change all children of a `Section` without calling any `notify`-calls and update the list manually with `notifyItemRangeRemoved`/`notifyItemRangeInserted`/`notifyItemRangeChanged`. This will require tracking of the old list size by the user. Something like this:

```java
public void updateSilently(@NonNull final Collection<? extends Group> newBodyGroups) {
    super.removeAll(children);
    children.clear();
    children.addAll(newBodyGroups);
    super.addAll(newBodyGroups);
}
```

and then

```kotlin
val section = Section()
val listOfItems = listOf(...)
section.updateSilently(listOfItems)
section.notifyChanged()
```

Or something like this which will inserts and removes items automatically and calls the `onAnimationChanged`-method of the `ItemAnimator` on those items which keep their position.

```java
public void refresh(@NonNull Collection<? extends Group> newBodyGroups) {
    final int oldItemCount = this.getItemCount();
    super.removeAll(this.children);
    this.children.clear();
    this.children.addAll(newBodyGroups);
    super.addAll(newBodyGroups);
    final int newItemCount = this.getItemCount();

    if (newItemCount > oldItemCount) {
        notifyItemRangeChanged(0, oldItemCount);
        notifyItemRangeInserted(oldItemCount, newItemCount);

    } else if (newItemCount < oldItemCount) {
        notifyItemRangeChanged(0, newItemCount);
        notifyItemRangeRemoved(newItemCount, oldItemCount);

    } else {
        this.notifyChanged();
    }

}
```

and then

```kotlin
val section = Section()
val listOfItems = listOf(...)
section.refresh(listOfItems)
```

>**Additional context**

**Comment by Zhuinden** [comment]
I'm actually slightly confused now that I read the code, considering `DiffUtil` **should** correctly dispatch `notifyItemChanged` for items that were, in fact, changed - and not just remove/inserted.

Theoretically, if you override `Item.getId()`, then it should correctly identify that the item is the same, and only match contents.

**Comment by Zhuinden** [comment]
I think this was added with https://github.com/lisawray/groupie/issues/365
