### ISSUE TITLE
how can i do a nested recyclerview?

### ISSUE THREAD

**Issue by cesarwillymc** [lisawray/groupie#371]
I am testing the library so far it can do this ..
![image](https://user-images.githubusercontent.com/48421004/100122853-84288f00-2e3f-11eb-8e39-18e8162f5b43.png)

I would like to achieve this ...

![image](https://user-images.githubusercontent.com/48421004/100123040-b934e180-2e3f-11eb-9db7-bb841bb9977e.png)

is Possible ? 

_FOR THE MOMENT I ONLY HAVE OR USE THESE LINES OF CODE_

**ADAPTADOR**
   rv_services_producr.apply {
            layoutManager = GridLayoutManager(this@MainActivity,adapterGrupie.spanCount).apply {
                spanSizeLookup= adapterGrupie.spanSizeLookup
                initialPrefetchItemCount= data.size
                isItemPrefetchEnabled=true
            }
            setHasFixedSize(true)
            adapter = adapterGrupie
        }
**//SET DATA**
 val section = Section()

           ExpandableGroup(AdapterProductosCategoria(this,variables),true).apply {

               section.addAll(convertItems(variables.items))
               add(section)
               adapterGrupie.add(this)

            }

**Comment by Zhuinden** [comment]
Hey hey!

I believe the trick is to, possibly unsurprisingly, use nested RecyclerView. 

Have 1 RecyclerView for the vertical, and have a horizontal RecyclerView in the items per each. 

If you have the items you need to show in the horizontal list per each item, then you can render it like any `class ConsumeableItem(val listItems: List<ListItemModel>) extends Item` and then show the list item models in the horizontal RecyclerView as you would with an adapter as you normally would.

Thankfully, horizontal RecyclerViews aren't too tricky, as when you replace their adapter, they effectively function as "the new view".

**Comment by cesarwillymc** [comment]
I implemented it with nested rv. but it was very slow :c

**Comment by Zhuinden** [comment]
Technically I am closing this because the `example` already contains `CarousalItem` which contains horizontal RecyclerView.
