### ISSUE TITLE
Call Fragment Method from class

### ISSUE THREAD

**Issue by SnorSnor9998** [lisawray/groupie#383]
I was able to call a method from a activity which is
(it.context as <activity_name>).<function_name>()

but i was wonder how to call the method from a fragment?

here is my code
`    
class BindCartItemList(val cartItem: CartList) : Item<GroupieViewHolder>() {

        override fun getLayout() = R.layout.ryr_cartlist_with_select

        override fun bind(viewHolder: GroupieViewHolder, position: Int) {

            viewHolder.itemView.ryr_product_name.text = cartItem.product?.productName
            viewHolder.itemView.ryr_quantity.setText(cartItem.quantity.toString())
            viewHolder.itemView.ryr_product_barcode.text = cartItem.product?.productBarcode

            //compact conversion
            val mConvert = FormatConversion()

            //default for display price and amount
            viewHolder.itemView.ryr_unit_price.text = mConvert.compactAmount(cartItem.product?.price!!)

            cartItem.amount = cartItem.quantity * cartItem.product?.price!!
            viewHolder.itemView.ryr_amount.text = mConvert.compactAmount(cartItem.amount)

            //quantity decrease
            viewHolder.itemView.ryr_btn_decrease.setOnClickListener {
                cartItem.quantity -= 1
                //not allow user set qty < 1
                if (cartItem.quantity < 1) {
                    cartItem.quantity = 1
                } else {
                    //once button press qty and amount will be change
                    viewHolder.itemView.ryr_quantity.setText(cartItem.quantity.toString())

                    cartItem.amount = cartItem.quantity * cartItem.product?.price!!
                    viewHolder.itemView.ryr_amount.text = mConvert.compactAmount(cartItem.amount)
                }
                (it.context as PosActivity).updateTotalAmount()
            }

            //quantity increase
            viewHolder.itemView.ryr_btn_increase.setOnClickListener {
                cartItem.quantity += 1
                viewHolder.itemView.ryr_quantity.setText(cartItem.quantity.toString())

                cartItem.amount = cartItem.quantity * cartItem.product?.price!!
                viewHolder.itemView.ryr_amount.text = mConvert.compactAmount(cartItem.amount)

                (it.context as PosActivity).updateTotalAmount()

            }

            //press container_1 for checkbox
            viewHolder.itemView.ryr_container_1.setOnClickListener {
                if (viewHolder.itemView.ryr_selected.isChecked) {
                    viewHolder.itemView.ryr_selected.isChecked = false
                    cartItem.selected = false
                } else if (!viewHolder.itemView.ryr_selected.isChecked) {
                    viewHolder.itemView.ryr_selected.isChecked = true
                    cartItem.selected = true
                }
            }

        }

    }
`

**Comment by Zhuinden** [comment]
Generally your data classes and therefore your `Item`s shouldn't be mutable, in that case, it'd look like so:

    class BindCartItemList(val cartItem: CartList, val actionHandler: ActionHandler) : Item<GroupieViewHolder>() {
        interface ActionHandler {
            fun onCartItemDecreaseClicked(cartItem: CartList)

            fun onCartItemIncreaseClicked(cartItem: CartList)

            fun onCartItemSelectionToggled(cartItem: CartList, shouldBeChecked: Boolean)
        }

        private val mConvert = FormatConversion() // compact conversion
    
        override fun getLayout() = R.layout.ryr_cartlist_with_select
    
        override fun bind(viewHolder: GroupieViewHolder, position: Int) {
   
            viewHolder.itemView.ryr_product_name.text = cartItem.product?.productName
            viewHolder.itemView.ryr_quantity.setText(cartItem.quantity.toString())
            viewHolder.itemView.ryr_product_barcode.text = cartItem.product?.productBarcode
    
            viewHolder.itemView.ryr_amount.text = mConvert.compactAmount(cartItem.quantity * cartItem.product?.price!!)
    
            //quantity increase
            viewHolder.itemView.ryr_btn_increase.setOnClickListener {
                actionHandler.onCartItemIncreaseClicked(cartItem)
            }
    
            //quantity decrease
            viewHolder.itemView.ryr_btn_decrease.setOnClickListener {
                actionHandler.onCartItemDecreaseClicked(cartItem)
            }

            //press container_1 for checkbox
            viewHolder.itemView.ryr_container_1.setOnClickListener {
                val isChecked = viewHolder.itemView.ryr_selected.isChecked
                actionHandler.onCartItemSelectionToggled(cartItem, !isChecked)
            }
        }    
    }

All other mutations belong outside of the adapter item, and could potentially be handled in the Fragment.

    class YourFragment: Fragment(), BindCartItemList.ActionHandler {
        ....

To update the item, you can either refresh the items in the adapter, or you can use `item.notifyChanged()`.

You should move the mutator methods I removed into the implementation of the interface (in this case, most likely the fragment).

**Comment by SnorSnor9998** [comment]
Thank, it help me a lot
