### ISSUE TITLE
Migrate off Bintray

### ISSUE THREAD

**Issue by Zhuinden** [lisawray/groupie#384]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Bintray is shutting down May 2021 along with JCenter.

As far as I'm aware, Groupie is hosted on JCenter, so a migration is needed.

**Comment by amitav13** [comment]
Any update here?

**Comment by Zhuinden** [comment]
Yes, apparently it's 2.9.0 on MavenCentral too.

Any further future trickery will be in regards to maintainers having to replace the publish process for any new versions, but that is not of relevance to consumers.

You should be able to use `mavenCentral` and it should just work.

**Comment by amitav13** [comment]
Ah my error is related to the android extensions artifact:
```
 Could not find com.xwray:groupie-kotlin-android-extensions:2.9.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/xwray/groupie-kotlin-android-extensions/2.9.0/groupie-kotlin-android-extensions-2.9.0.pom
       - https://repo.maven.apache.org/maven2/com/xwray/groupie-kotlin-android-extensions/2.9.0/groupie-kotlin-android-extensions-2.9.0.pom
       - https://jitpack.io/com/xwray/groupie-kotlin-android-extensions/2.9.0/groupie-kotlin-android-extensions-2.9.0.pom
```

but this has been deprecated anyway right?

**Comment by lukasz-kalnik-gcx** [comment]
> Yes, apparently it's 2.9.0 on MavenCentral too.
> 
> Any further future trickery will be in regards to maintainers having to replace the publish process for any new versions, but that is not of relevance to consumers.
> 
> You should be able to use `mavenCentral` and it should just work.
> 
> See https://mvnrepository.com/artifact/com.xwray/groupie/2.9.0

mvnrepository still references the JCenter artifact:
![image](https://user-images.githubusercontent.com/70261110/115837357-c8cd4c00-a418-11eb-8336-6df4970b1a5d.png)

Groupie is still not available on MavenCentral:
https://search.maven.org/search?q=g:com.xwray%20AND%20a:groupie

**Comment by Zhuinden** [comment]
Oh... well that is a problem.

I do not own xwray.com, Lisa Wray does, I wonder if she's available for migrating the library to MavenCentral.

If she's unavailable and I get really desperate, I'll just move it to Jitpack. 🤔

**Comment by lukasz-kalnik-gcx** [comment]
Can you just release it through GitHub packages?

**Comment by vyshas** [comment]
@Zhuinden can we move this to Jipack for now as there would be projects that are still using groupie and migrating off Bintray/ jcenter in this month.

**Comment by Zhuinden** [comment]
Yes, I intended to, I was just massively hit with a bunch of other things I *had* to do. 

But I'll really try to do it on friday. I've heard about github packages requiring some auth tokens to work, so I don't really want to have to figure that out. 🤔

**Comment by yshrsmz** [comment]
The good news is that bintray(readonly) is going to be available for the foreseeable future.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

If Lisa Wray is not maintaining the lib anymore and that causes current maintainers some difficulties, why not just create a new org and change the package name?

**Comment by Zhuinden** [comment]
I have done the necessary changes to make things work with Jitpack.

It seems to mostly be the following steps:

1.) add `jitpack.io` to repositories

2.) change build.gradle dependencies from `com.xwray` to `com.github.lisawray.groupie`, like so: `implementation "com.github.lisawray.groupie:groupie:$groupie_version"`

**Comment by Sash0k** [comment]
trying to download from Jitpack, got an error.

> Could not GET 'https://jitpack.io/com/github/groupie/2.9.0/groupie-2.9.0.pom'. Received status code 401 from server: Unauthorized

is it public?
