### ISSUE TITLE
setHeader dosen't show header when trying to setHeader after fetching data async

### ISSUE THREAD

**Issue by HoseinHaqiqian** [lisawray/groupie#387]
I am trying to add/set header to list after fetching header data from api, but after setting header i need to scroll down, then up to see header.
is there any approach to avoid scrolling?

notifying method's is not working.

**Comment by Zhuinden** [comment]
Hey, by `setHeader` do you mean using a Section?

**Comment by HoseinHaqiqian** [comment]
@Zhuinden yes, setHeader inside a section i mean

**Comment by HoseinHaqiqian** [comment]
Any Idea to fix this?

**Comment by Zhuinden** [comment]
If the notify doesn't trigger a change, that would mean that `hasSameContentAs` is implemented in such a way that despite two headers being different, they are said to be the same. 

Make sure you are not mutating the header if you are using `update`/`updateAsync`. You can verify that this is the cause of the issue if you try using `replaceAll` (which will kill animations, but makes changes immediate9.

**Comment by Zhuinden** [comment]
My personal recommendation would be to not use Section, and instead use a separate `Item` for the header, and a separate `Item` for the items. We pretty much don't use Section ourselves, although as a maintainer I have to keep it alive(?).

**Comment by Zhuinden** [comment]
What was the solution on your side?

**Comment by HoseinHaqiqian** [comment]
Sorry for late response.
In my case, I had to use sections, so I have added another section to the top of my adapter.
now I have 2 sections, header and main, thanks. main section is for items.
