### ISSUE TITLE
Why does a BindableItem<ViewBinding> class ask for the layout?

### ISSUE THREAD

**Issue by jeevansurendran** [lisawray/groupie#389]
Why was it enforced that we also need to override `getLayout()` ?

**Comment by Zhuinden** [comment]
Hey! Most likely because the `getLayout` is used as the default `viewType`. 🤔 

https://github.com/lisawray/groupie/pull/325/files#diff-e223bce9e6dd020a086b9c7d813710bf3c8a950b635d5dba22c9662564923f4fR20

**Comment by jeevansurendran** [comment]
Got it! But I feel the initilizeViewBinding where we manually set the view is a little redundant. can something like this be done? 🤔 

Epoxy did something like this which makes more sense. https://github.com/airbnb/epoxy/blob/master/kotlinsample/src/main/java/com/airbnb/epoxy/kotlinsample/models/ItemViewBindingEpoxyHolder.kt

**Comment by Yundin** [comment]
When using custom view for Item, I have to create dummy xml with just one view to handle getLayout(). It would be great to be able to create ViewHolder from context right inside Item.
