### ISSUE TITLE
Installation instructions are not complete

### ISSUE THREAD

**Issue by kuteki707** [lisawray/groupie#391]
The Gradle setup for Kotlin does not specify the `mavenCentral()` under the `repositories`. Also it does not mention the `mavenCentral()` and `maven { url "https://jitpack.io" }` under the `allprojects` `repositories`.

**Comment by Zhuinden** [comment]
You're correct, `allprojects {` should have been there from the getgo.

Fixed in https://github.com/lisawray/groupie/commit/b6f7f7217c28898fd8d89be0ff1180843a82cad6
