### ISSUE TITLE
Animate section groups when calling update

### ISSUE THREAD

**Issue by wishygupta** [lisawray/groupie#394]
I want to animate the section when I update using the `postSection.update(postsGroup)`
I don't the whole recycler view elements to animate just the views contained in Section group
How can I do that?

**Comment by Zhuinden** [comment]
I don't know why I am not getting notified of anything these days, but I'd generally just recommend using `Item`s instead of `Section`. Because of the nested nature of `Section`, I think you have more control if you keep them as `Item`.
