### ISSUE TITLE
Jcenter is deprecated

### ISSUE THREAD

**Issue by HashirLabs** [lisawray/groupie#395]
Hi

When are we moving the lib from jcenter to any other repository providers like google, maven etc

**Comment by nullptr2this** [comment]
@HashirLabs It look as if there are artifacts available on jitpack.io in lieu of jcenter.

**Comment by Zhuinden** [comment]
The library is indeed available on Jitpack, as described in the readme

**Comment by HashirLabs** [comment]
got it, closing it now , thanks
