### ISSUE TITLE
Warning: Raw use of parameterized class 'GroupAdapter'

### ISSUE THREAD

**Issue by amirdora** [lisawray/groupie#403]
**Describe the bug**
This is not exactly a bug but a warning message i get often from Android studio.

Whenever I create new instance of GroupAdapter, i.e `groupAdapter = new GroupAdapter();` android studio shows the following warning message. 

> Warning:(131, 28) Raw use of parameterized class 'GroupAdapter'

**To Reproduce**
Create new instance of GroupAdapter
`GroupAdapter groupAdapter = new GroupAdapter();
`
**Expected behavior**
No warning should appear ideally.

**Library version**
2.9.0

**Additional context**

**Comment by Zhuinden** [comment]
If you are looking to use that in that format, prefer `GroupieAdapter` that supplies a default and sane generic argument.

Also, I can't believe this issue is from 9 days ago. This new Github notification ui is an absolute nightmare.
