### ISSUE TITLE
I'm trying to implement. But not some error...

### ISSUE THREAD

**Issue by Kirito-Excalibur** [lisawray/groupie#415]
Failed to resolve: com.github.lisawray.groupie:groupie-databinding:2.10.0
"open.dependency.in.project.structure"
Affected Modules: "openFile:C:/Users/Kirito/AndroidStudioProjects/KotlinMessenger/app/build.gradle"

**Comment by XenioxYT** [comment]
+1 I'm having the same issue on Android Studio. I tried adding jcenter() to the repositories however no luck...

**Comment by Canivek** [comment]
Did you add JitPack as a repository? 
```
  repositories {
      maven { url 'https://jitpack.io' }
  }
```

**Comment by Canivek** [comment]
@XenioxYT Your project is both using the old (build.gradle) and new (settings.gradle) way to declare repositories. In your top level build.gradle, you can remove the `allprojects` block and you should add JitPack in your settings.gradle file (under `dependencyResolutionManagement.repositories`).
And you don't need `jcenter()` to use the last version of Groupie.

**Comment by XenioxYT** [comment]
@Canivek That got it! Thank you so much!

**Comment by Kirito-Excalibur** [comment]
@Canivek 
Another error
Build was configured to prefer settings repositories over project repositories but repository 'maven' was added by build file 'app\build.gradle'

**Comment by Kirito-Excalibur** [comment]
I got it. My android studio was not updated.
