### ISSUE TITLE
UpdatingGroup should implement add, addAll, remove, etc

### ISSUE THREAD

**Issue by lisawray** [lisawray/groupie#58]
Either to support them, or throw an Exception and say they're not supported.  In the latter case, we should consider whether it should really extend NestedGroup.

**Comment by lisawray** [comment]
Also, if it continues to extend NestedGroup, it should probably accept a List<Group> and perform the diff on the flat list of Items produced at the time of insertion.  Later diffs should calculate the last flat list items and diff against that.

**Comment by kari4758** [comment]
Hi Lisa, can I ask you what is the plan for this issue? :)
Is there any existing group/section that can support `add/addAll` and `update`?
Or can I use `DiffUtil` on `Section`? (I couldn't figure out how to use `DiffUtil` for `Section`.)
I think it is too expensive to call `update` every time new items are added to the end of the list.

**Comment by lisawray** [comment]
HI @kari4758. I hope to address this in 2.0 very soon. 

As you suggested, I'm thinking of just adding update capability to Section.  That would mean UpdatingGroup would either be deprecated or removed.  

Any objections?

**Comment by kari4758** [comment]
> I'm thinking of just adding update capability to Section

That sounds great 🗡 
Thanks for making this great library.
So excited to see this update on 2.0.

**Comment by denimwho** [comment]
@lisawray I just wanted to know if this functionality is available now in section.
I would also like to know how to clear previous items except header, footer and placeholder, and new items in section.

**Comment by denimwho** [comment]
The solution I found is to use Updating Group.

**Comment by lisawray** [comment]
Add update capability for Section: https://github.com/lisawray/groupie/pull/130
