### ISSUE TITLE
Allow divider item

### ISSUE THREAD

**Issue by mattinger** [lisawray/groupie#62]
It would be nice for a given Section to allow 3 different divider items:
1.  After the header
2.  Before the footer
3.  Between each item

I realize you could build 1 and 2 into the layouts for the header and footer, and that for 3, you could create a custom Item object and place it in between each content item, but it seems like it would be simplier to just say:

setHeaderDivider(Item item)
setFooterDivider(Item item)
setItemDivider(Item item)

**Comment by lisawray** [comment]
Is there a reason you don't want to use an `ItemDecoration`?  That seems like the most canonical approach to this with a RecyclerView (and what I currently use myself).

**Comment by lisawray** [comment]
Closing this for now—if this didn't answer your question, feel free to reply or open another issue!

**Comment by slavasav** [comment]
Sorry for commenting on an old question, but there is a valid use case for specifically Section dividers: when there are several sections it is the section that has the information about header/footer/items, the ItemDecoration on the whole RecyclerView in this case lacks all of that.
