### ISSUE TITLE
Auto scroll to top with no add operation

### ISSUE THREAD

**Issue by chowaikong** [lisawray/groupie#68]
My problem is that I have three fragments in an Activity, they all contains a RecyclerView which contains two groups of RecyclerView, these RecyclerViews were data loaded and scroll to the bottom, but when I switch these three fragments, the second RecyclerView they contains will automatically scroll to the top while no add or other operation, and the first RecyclerView is not visible. Currently I have no idea why this happened, any help?

**Comment by chowaikong** [comment]
And there is another problem, these two RecyclerViews supposes to be display in order, although  data was requested asynchronously, but actually don't, the order will mess up.

**Comment by lisawray** [comment]
Hey @chowaikong -- it's hard for me to picture what you're describing without an example or some code.  If you can post a demo project, I'm happy to take a look at it!

**Comment by chowaikong** [comment]
Here is my project https://github.com/chowaikong/ZMZ

**Comment by lisawray** [comment]
I'll take a look at it tonight!  Thanks for posting

**Comment by lisawray** [comment]
@chowaikong , I pulled down your project and tried to run it, but without your private API keys, it can't compile.  Without being able to load content or see the error, I'm not sure I can help you.  

If you can isolate an example of the behavior you believe is wrong, I'm happy to look at a small example or a video.

**Comment by chowaikong** [comment]
I made a [GIF](http://ezgif.com/save/ezgif.com-77b001fd16.gif) so you can take a look at it, you can see the RecyclerView in the second tab will auto scroll to item's top.

**Comment by lisawray** [comment]
@chowaikong I just get "File not found"

**Comment by chowaikong** [comment]
The GIF download address: http://ezgif.com/save/ezgif.com-77b001fd16.gif

**Comment by lisawray** [comment]
Sorry, I see the exact same thing!  I think that website only generates GIFs -- not hosts them. You may have to place the GIF somewhere else, like [Imgur](http://imgur.com/)

**Comment by chowaikong** [comment]
I uploaded a [video](video).

**Comment by lisawray** [comment]
I don't think this issue is related to the library.  From best I can tell, the jumping could be related to RecyclerView changing focus to a focusable item.  You could try adding `android:descendantFocusability="beforeDescendants"` to your RecyclerView and see if that helps.

Sorry I can't be of more help with what you've provided.  If you're able to reproduce this problem in a minimal example project, I can take another look.
