### ISSUE TITLE
Item decoration's height growth when scroll

### ISSUE THREAD

**Issue by chowaikong** [lisawray/groupie#70]
Problem here is that I scroll the vertical RecyclerView from top to bottom again and again, the item decoration which is a customized space gap item decoration will get bigger height each time, the customized decoration's code are below:  
```java
public class VerticalSpaceItemDecoration extends RecyclerView.ItemDecoration {
  private final int mVerticalSpaceHeight;

  public VerticalSpaceItemDecoration(int mVerticalSpaceHeight) {
    this.mVerticalSpaceHeight = mVerticalSpaceHeight;
  }

  @Override
  public void getItemOffsets(Rect outRect, View view, RecyclerView parent,
      RecyclerView.State state) {
    outRect.bottom = mVerticalSpaceHeight;
  }
}
```

Seems groupie is more buggy in my code.

**Comment by lisawray** [comment]
@chowaikong Sorry for the super delay on responding here!

Groupie should not affect your item decorations.  My first guess is that you are accidentally attaching the item decoration more than once.  You could add some logging to try and figure out if this is the case.

**Comment by ismdcf** [comment]
For those who are facing this issue, it could be because you are adding the item decoration view every time there is an update to your data  (which is bad). But as a quick fix you could check if the recycler view has any item decorators added and if not you could add yours 

` 
 if (recycylerView.getItemDecorationCount()<1){
            recycylerView.addItemDecoration(
                    new InsetItemDecoration(
                            ContextCompat.getColor(getActivity(),R.color.primary_background_color),
                            getResources().getDimensionPixelSize(R.dimen.padding_small),
                            INSET_TYPE_KEY,
                            INSET));
        }
`
