### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void com.genius.groupie.OnItemClickListener.onItemClick(com.genius.groupie.Item, android.view.View)' on a null object reference

### ISSUE THREAD

**Issue by yiyinying** [lisawray/groupie#75]
adapter.setOnItemClickListener(new OnItemClickListener() {
      @Override public void onItemClick(Item item, View view) {
        Toast.makeText(MainActivity.this, "down", Toast.LENGTH_SHORT).show();
      }
    });

onItemClickListener a error

**Comment by lisawray** [comment]
Fixed in https://github.com/lisawray/groupie/pull/72.  Thanks for reporting!  Will be fixed in 1.0
