### ISSUE TITLE
is not good

### ISSUE THREAD

**Issue by yiyinying** [lisawray/groupie#77]
onClick error

**Comment by Teovald** [comment]
🤔

**Comment by lisawray** [comment]
Hi @yiyinying , I'm currently waiting for the new library to sync to JCenter / Maven central. I had to apply again for inclusion after changing the package name.  

The new gradle details will be `compile 'com.xwray:groupie:1.0.0'` :crossed_fingers: 

Thank you for your patience. :)

**Comment by lisawray** [comment]
Actually, if you want to use it right now, you can use it directly from bintray.  

    repositories {
        maven {
            url  "http://dl.bintray.com/lisawray/maven"
        }
    }

`compile 'com.xwray:groupie:1.0.0'`

bam!
