### ISSUE TITLE
Multiple ViewHolder for Single Item

### ISSUE THREAD

**Issue by bhavinwebdesk** [lisawray/groupie#95]
Hello @lisawray ,

Thanks for nice library. I want to ask question that is it possible to return different layout for same model class?
My use case is : 
I have to show products and it may with picture and without picture.

Is is possible now or is any feature request for it?

Thanks,
Bhavin

**Comment by lisawray** [comment]
Sure!  If you're using the current production version with databinding, just make an `Item<ViewDataBinding>` and switch the layout depending on your case.  Something like this:

    public class Item<ViewDataBinding> {

        private Product product;

        public int getLayout() {
            return product.hasPicture() ? R.layout.item_picture : R.layout.item_no_picture;
        }

        public void bind(ViewDataBinding binding, int position) {
           binding.setVariable(BR.product, product);
        }
    }

**Comment by lisawray** [comment]
Closing since I think I answered your question!  If you have more questions please open another issue or reopen this one :)
