### ISSUE TITLE
any tips for item dragging (Question)

### ISSUE THREAD

**Issue by iskuhis** [lisawray/groupie#98]
I want to have items drag part to sort items in RecyclerView, when  user touching particular part(ImageView) of RecyclerView item

**Comment by lisawray** [comment]
There's no special support for dragging in Groupie today. You implement dragging just like in any other RecyclerView. You should use ItemTouchHelper.

Here's a tutorial on dragging: https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf
And part 2, which explains how to create a handle: https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-6a6f0c422efd

**Comment by IskuhiS** [comment]
Thanks, I see the sample,  but have question
 I found 
itemTouchHelper.startDrag(viewHolder);
where viewHolder is passed from adapter when user touches on item 
if I attach touchListener for example in HeartCardItem ,I can attach touchListener
to view and could not pass viewHolder, while I need viewHolder for itemTouchHelper.startDrag(viewHolder);
